### ISSUE TITLE
Miner?

### ISSUE THREAD

**Issue by rapososoftwares** [guigo613/alternative-wa-version#2]
I would just like to know why my system with the original files only use 2GB of my RAM, and with these files are using 100% of the memory?
Regardless of the amount of memory I add to the server, it will always be using 100%

**Comment by guigo613** [comment]
What? This is just HTML and JS to run in a browser, exactly the same code that WhatsApp itself provides with one single difference: instead of the JS being pulled externally, it's located locally in the HTML so that corrections can be added.

The content is all available; feel free to analyze the code before making accusations. Grab the original files and compare; if you need help, I can assist in showing that they are the same files, and feel free to analyze them.
